baseURL: "https://m-hisham08.github.io/"
title: "scribesByHisham."
paginate: 5
theme: PaperMod

params:
  defaultTheme: auto
  enableSearch: true
  ShowReadingTime: true
  ShowShareButtons: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowPostNavLinks: true
  ShowToc: true
  ShowMetadata: true
  ShowTaxonomies: true

  editPost:
    URL: "https://github.com/<path_to_repo>/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    # limit: 10 # refer: https://www.fusejs.io/api/methods.html#search
    keys: ["title", "permalink", "summary", "content"]

  homeInfoParams:
    Title: Hello There!
    Content: "Welcome to my personal blog! My name is Mohammad Hisham, and I am a Computer Science Engineering undergraduate based in India. Here, I share my thoughts on both tech and non-tech topics. Feel free to explore my recent posts!"

  socialIcons:
    - name: linkedin
      url: "https://linkedin.com/in/mhisham08"
    - name: github
      url: "https://github.com/m-hisham08"

menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 120
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 30
    - identifier: search
      name: Search
      url: /search/
      weight: 10

outputs:
  home:
    - HTML
    - RSS
    - JSON # necessary for search

